### ISSUE TITLE
Submitting TipCalculator app for review

### ISSUE THREAD

**Issue by dhui** [dhui/codepath-tipcalculator#1]
@nesquena @timothy1ee

Great tutorial guys! Was quite simple to follow.

**Comment by timothy1ee** [comment]
Dale, I don't see your SettingsViewController, can you check if you pushed all your code?

**Comment by dhui** [comment]
Whoops! Forgot to implement it... My bad. I'll get it done sometime this week and will comment on the this issue once my changes have been pushed.

**Comment by dhui** [comment]
@nesquena @timothy1ee 

I've now added a the settings view.
The default tip percentage will only be saved if you tap on the save button. I also display the current default tip percentage so the user will be aware of any differences if they decide to "cancel" saving the default tip percentage.

**Comment by timothy1ee** [comment]
Great, thanks for the submission! Hopefully, this gave you a sense for the basic iOS development process.

The next step is to schedule a 15 minute phone interview here: https://www.google.com/calendar/selfsched?sstoken=UVBDTi1jVkx4SldqfGRlZmF1bHR8MGVhNTlkZDFmYzQzODdkNDFhZjQ0NWQyZjFiMDU3Nzg. Let me know if none of those slots work.

When you choose a slot, can you edit the event with your phone number? Look forward to chatting!
